### ISSUE TITLE
Ability to enable for just a group of users, not for all users on the server

### ISSUE THREAD

**Issue by mrvahedi68** [pondersource/sciencemesh-nextcloud#181]
Select groups in the administration panel of Siencemesh and enable the app only for users of these groups.

**Comment by michielbdejong** [comment]
I did find this: https://github.com/owncloud/core/blob/ab9763b2b4d27a221bf12005eddd2bb7d319d286/lib/private/App/AppManager.php#L227
That might work out-of-the-box on Nextcloud, but not on ownCloud because there we have a switch in config.php that determines whether the
server will try to use the app. So if that switch is globally set to true, and the app is then disabled for some users, it would just lead to a 'class not found' error.

**Comment by michielbdejong** [comment]
So this code works around the 'enabled' column in the `oc_appconfig` database table. You can start by adding a JSON-encoded array of group names there, and then calling the `isAppEnabledForUser` function inside the SciencemeshShareProviderFactory. You should see that the app is not enabled if the user is not in the group.

Once you have that confirmed on both NC and OC-10 you can add the consequence to that: if the app is not enabled, then just refer to the existing default ShareProviderFactory.

**Comment by parhamin2010** [comment]
@michielbdejong is it possible to do it on ScienceMeshApp.php file instead of do this complex structure?
I found this solution:
`
// Get the user session
$userSession = \OC::$server->getUserSession();

// Get the current user's groups
$userGroups = $userSession->getGroups();

// Check if the user belongs to a restricted group
$restrictedGroup = 'restricted-group-name';
if (in_array($restrictedGroup, $userGroups)) {
    // User belongs to the restricted group, disable the app
    \OC::$server->getAppManager()->disableApp('myapp');
}
`

**Comment by parhamin2010** [comment]
Here's the guide for having this feature on Apps in Nextcloud:
You can find it under Settings > apps 
![image](https://user-images.githubusercontent.com/25672014/232846177-26e3c6f4-0e37-4131-9321-c70b7702b531.png)

And OwnCloud:
![image](https://user-images.githubusercontent.com/25672014/232846239-e0412b2d-e4d3-4e9e-878d-845b04508a4d.png)
